services:
  php:
    image: php:8.3-fpm-alpine
    volumes:
      - ./src:/var/www/html
    networks:
      - web
    environment:
      API_URL: http://localhost:8000

  nginx:
    image: nginx:1.25-alpine
    ports:
      # Realizei a troca da porta 80 pela 8080 pois estava dando conflito com outros projetos Apache que tenho
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - web

networks:
  web:
    driver: bridge
