services:
  php:
    image: php:8.3-fpm-alpine
    command: sh -c "docker-php-ext-install pdo_mysql && php-fpm"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - api
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: linkmark_api
      DB_PASSWORD: linkmark
      DB_NAME: linkmark
      FRONTEND_URL: http://localhost:80

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - api

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: linkmark
      MYSQL_USER: linkmark_api
      MYSQL_PASSWORD: linkmark
      MYSQL_ROOT_PASSWORD: linkmark
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  mysql_data:
